=== gnardin/emilia/src/main/resources/conf/emilia.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">

	<element name="emilia">
		<complexType>
			<sequence>
				<element name="eventClassifierClass" type="string" />
				<element name="normRecognitionClass" type="string" />
				<element name="normAdoptionClass" type="string" />
				<element name="normSalienceClass" type="string" />
				<element name="normEnforcementClass" type="string" />
				<element name="normComplianceClass" type="string" />
				<element name="normativeBoardClass" type="string" />
			</sequence>
		</complexType>
	</element>
</schema>

=== gnardin/emilia/src/main/resources/conf/emilia.xml
<?xml version="1.0" encoding="UTF-8"?>
<emilia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="emilia.xsd">

	<eventClassifierClass>examples.pgg.modules.classifier.EventClassifier</eventClassifierClass>
	<normRecognitionClass>examples.pgg.modules.recognition.NormRecognitionController</normRecognitionClass>
	<normAdoptionClass>examples.pgg.modules.adoption.NormAdoptionController</normAdoptionClass>
	<normSalienceClass>examples.pgg.modules.salience.NormSalienceController</normSalienceClass>
	<normEnforcementClass>examples.pgg.modules.enforcement.NormEnforcementController</normEnforcementClass>
	<normComplianceClass>examples.pgg.modules.compliance.NormComplianceController</normComplianceClass>
	<normativeBoardClass>examples.pgg.board.NormativeBoard</normativeBoardClass>
</emilia>

=== gnardin/emilia/src/main/resources/conf/pgg/emilia.xml
<?xml version="1.0" encoding="UTF-8"?>
<emilia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="emilia.xsd">

	<eventClassifierClass>emilia.defaultImpl.modules.classifier.EventClassifier</eventClassifierClass>
	<normRecognitionClass>emilia.defaultImpl.modules.recognition.NormRecognitionController</normRecognitionClass>
	<normAdoptionClass>emilia.defaultImpl.modules.adoption.NormAdoptionController</normAdoptionClass>
	<normSalienceClass>emilia.defaultImpl.modules.salience.NormSalienceController</normSalienceClass>
	<normEnforcementClass>emilia.defaultImpl.modules.enforcement.NormEnforcementController</normEnforcementClass>
	<normComplianceClass>emilia.defaultImpl.modules.compliance.NormComplianceController</normComplianceClass>
	<normativeBoardClass>emilia.defaultImpl.board.NormativeBoard</normativeBoardClass>
</emilia>

=== gnardin/emilia/src/main/resources/conf/ijcai11/emilia.xml
<?xml version="1.0" encoding="UTF-8"?>
<emilia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="emilia.xsd">

	<eventClassifierClass>emilia.defaultImpl.modules.classifier.EventClassifier</eventClassifierClass>
	<normRecognitionClass>examples.ijcai11.modules.recognition.NormRecognitionController</normRecognitionClass>
	<normAdoptionClass>emilia.defaultImpl.modules.adoption.NormAdoptionController</normAdoptionClass>
	<normSalienceClass>emilia.defaultImpl.modules.salience.NormSalienceController</normSalienceClass>
	<normEnforcementClass>examples.ijcai11.modules.enforcement.NormEnforcementController</normEnforcementClass>
	<normComplianceClass>emilia.defaultImpl.modules.compliance.NormComplianceController</normComplianceClass>
	<normativeBoardClass>emilia.defaultImpl.board.NormativeBoard</normativeBoardClass>
</emilia>

=== gnardin/emilia/src/main/resources/conf/topology/emilia.xml
<?xml version="1.0" encoding="UTF-8"?>
<emilia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="emilia.xsd">

	<eventClassifierClass>examples.topology.modules.classifier.EventClassifier</eventClassifierClass>
	<normRecognitionClass>examples.topology.modules.recognition.NormRecognitionController</normRecognitionClass>
	<normAdoptionClass>examples.topology.modules.adoption.NormAdoptionController</normAdoptionClass>
	<normSalienceClass>examples.topology.modules.salience.NormSalienceController</normSalienceClass>
	<normEnforcementClass>examples.topology.modules.enforcement.NormEnforcementController</normEnforcementClass>
	<normComplianceClass>examples.topology.modules.compliance.NormComplianceController</normComplianceClass>
	<normativeBoardClass>examples.topology.board.NormativeBoard</normativeBoardClass>
</emilia>
